name: Build and Release

on:
  push:
    tags:
      - 'v*'

# 添加权限配置
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6
        pip install nuitka
        pip install zstandard
        pip install -i https://pypi.org/simple/ PyQt6-Fluent-Widgets
    
    - name: Run tests
      run: |
        python -m pytest tests/ --cov=src
    
    - name: Build with Nuitka
      shell: cmd
      run: >-
        python scripts/build.py
    
    - name: List Build Directory
      run: |
        dir build
      shell: cmd

    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')  
      uses: softprops/action-gh-release@v1
      with:
        files: build/*.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 